version: '3.9'

services:
  database_soujunior:
    image: postgres:16
    container_name: database_soujunior
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=mentores_backend
    volumes:
      - pgdata:/var/lib/postgresql/data

  mentores_backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mentores_backend
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    depends_on:
      - database_soujunior
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://docker:ignite@database_soujunior:5432/mentores_backend

volumes:
  pgdata:
