export enum AuthErrorCodeEnum {
  ACCOUNT_BLOCKED = 'AUTH_ACCOUNT_BLOCKED',
  ACCOUNT_NOT_CONFIRMED = 'AUTH_ACCOUNT_NOT_CONFIRMED',
  INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  PASSWORD_ATTEMPT_WARNING = 'AUTH_PASSWORD_ATTEMPT_WARNING',
  PROFILE_NOT_FOUND = 'AUTH_PROFILE_NOT_FOUND',
  PROFILE_PAUSED = 'AUTH_PROFILE_PAUSED',
}
